// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: model.proto at 83:1
package com.tevinjeffrey.rutgersct.data.uctapi.model;

import android.os.Parcelable;
import android.support.annotation.Nullable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import okio.ByteString;

public final class Book extends AndroidMessage<Book, Book.Builder> {
  public static final ProtoAdapter<Book> ADAPTER = new ProtoAdapter_Book();

  public static final Parcelable.Creator<Book> CREATOR = AndroidMessage.newCreator(ADAPTER);
  public static final Long DEFAULT_ID = 0L;
  public static final Long DEFAULT_SECTION_ID = 0L;
  public static final String DEFAULT_TITLE = "";
  public static final String DEFAULT_URL = "";
  private static final long serialVersionUID = 0L;
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  @Nullable
  public final Long id;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  @Nullable
  public final Long section_id;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @Nullable
  public final String title;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @Nullable
  public final String url;

  public Book(
      @Nullable Long id,
      @Nullable Long section_id,
      @Nullable String title,
      @Nullable String url) {
    this(id, section_id, title, url, ByteString.EMPTY);
  }

  public Book(
      @Nullable Long id,
      @Nullable Long section_id,
      @Nullable String title,
      @Nullable String url,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
    this.section_id = section_id;
    this.title = title;
    this.url = url;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) {
      return true;
    }
    if (!(other instanceof Book)) {
      return false;
    }
    Book o = (Book) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(id, o.id)
        && Internal.equals(section_id, o.section_id)
        && Internal.equals(title, o.title)
        && Internal.equals(url, o.url);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (section_id != null ? section_id.hashCode() : 0);
      result = result * 37 + (title != null ? title.hashCode() : 0);
      result = result * 37 + (url != null ? url.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.section_id = section_id;
    builder.title = title;
    builder.url = url;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) {
      builder.append(", id=").append(id);
    }
    if (section_id != null) {
      builder.append(", section_id=").append(section_id);
    }
    if (title != null) {
      builder.append(", title=").append(title);
    }
    if (url != null) {
      builder.append(", url=").append(url);
    }
    return builder.replace(0, 2, "Book{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Book, Builder> {
    public Long id;

    public Long section_id;

    public String title;

    public String url;

    public Builder() {
    }

    @Override
    public Book build() {
      return new Book(id, section_id, title, url, super.buildUnknownFields());
    }

    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    public Builder section_id(Long section_id) {
      this.section_id = section_id;
      return this;
    }

    public Builder title(String title) {
      this.title = title;
      return this;
    }

    public Builder url(String url) {
      this.url = url;
      return this;
    }
  }

  private static final class ProtoAdapter_Book extends ProtoAdapter<Book> {
    ProtoAdapter_Book() {
      super(FieldEncoding.LENGTH_DELIMITED, Book.class);
    }

    @Override
    public Book decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1; ) {
        switch (tag) {
          case 1:
            builder.id(ProtoAdapter.INT64.decode(reader));
            break;
          case 2:
            builder.section_id(ProtoAdapter.INT64.decode(reader));
            break;
          case 3:
            builder.title(ProtoAdapter.STRING.decode(reader));
            break;
          case 4:
            builder.url(ProtoAdapter.STRING.decode(reader));
            break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public void encode(ProtoWriter writer, Book value) throws IOException {
      if (value.id != null) {
        ProtoAdapter.INT64.encodeWithTag(writer, 1, value.id);
      }
      if (value.section_id != null) {
        ProtoAdapter.INT64.encodeWithTag(writer, 2, value.section_id);
      }
      if (value.title != null) {
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.title);
      }
      if (value.url != null) {
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.url);
      }
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public int encodedSize(Book value) {
      return (value.id != null ? ProtoAdapter.INT64.encodedSizeWithTag(1, value.id) : 0)
          + (value.section_id != null ? ProtoAdapter.INT64.encodedSizeWithTag(2, value.section_id)
                                      : 0)
          + (value.title != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.title) : 0)
          + (value.url != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.url) : 0)
          + value.unknownFields().size();
    }

    @Override
    public Book redact(Book value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
