// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: model.proto at 65:1
package com.tevinjeffrey.rutgersct.data.uctapi.model;

import android.os.Parcelable;
import android.support.annotation.Nullable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class Meeting extends AndroidMessage<Meeting, Meeting.Builder> {
  public static final ProtoAdapter<Meeting> ADAPTER = new ProtoAdapter_Meeting();

  public static final Parcelable.Creator<Meeting> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_ID = 0L;

  public static final Long DEFAULT_SECTION_ID = 0L;

  public static final String DEFAULT_ROOM = "";

  public static final String DEFAULT_DAY = "";

  public static final String DEFAULT_START_TIME = "";

  public static final String DEFAULT_END_TIME = "";

  public static final String DEFAULT_CLASS_TYPE = "";

  public static final Integer DEFAULT_INDEX = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  @Nullable
  public final Long id;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  @Nullable
  public final Long section_id;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @Nullable
  public final String room;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @Nullable
  public final String day;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @Nullable
  public final String start_time;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @Nullable
  public final String end_time;

  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @Nullable
  public final String class_type;

  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  @Nullable
  public final Integer index;

  @WireField(
      tag = 9,
      adapter = "com.tevinjeffrey.rutgersct.data.uctapi.model.Metadata#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<Metadata> metadata;

  public Meeting(@Nullable Long id, @Nullable Long section_id, @Nullable String room, @Nullable String day, @Nullable String start_time, @Nullable String end_time, @Nullable String class_type, @Nullable Integer index, List<Metadata> metadata) {
    this(id, section_id, room, day, start_time, end_time, class_type, index, metadata, ByteString.EMPTY);
  }

  public Meeting(@Nullable Long id, @Nullable Long section_id, @Nullable String room, @Nullable String day, @Nullable String start_time, @Nullable String end_time, @Nullable String class_type, @Nullable Integer index, List<Metadata> metadata, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
    this.section_id = section_id;
    this.room = room;
    this.day = day;
    this.start_time = start_time;
    this.end_time = end_time;
    this.class_type = class_type;
    this.index = index;
    this.metadata = Internal.immutableCopyOf("metadata", metadata);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.section_id = section_id;
    builder.room = room;
    builder.day = day;
    builder.start_time = start_time;
    builder.end_time = end_time;
    builder.class_type = class_type;
    builder.index = index;
    builder.metadata = Internal.copyOf("metadata", metadata);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Meeting)) return false;
    Meeting o = (Meeting) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(id, o.id)
        && Internal.equals(section_id, o.section_id)
        && Internal.equals(room, o.room)
        && Internal.equals(day, o.day)
        && Internal.equals(start_time, o.start_time)
        && Internal.equals(end_time, o.end_time)
        && Internal.equals(class_type, o.class_type)
        && Internal.equals(index, o.index)
        && metadata.equals(o.metadata);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (section_id != null ? section_id.hashCode() : 0);
      result = result * 37 + (room != null ? room.hashCode() : 0);
      result = result * 37 + (day != null ? day.hashCode() : 0);
      result = result * 37 + (start_time != null ? start_time.hashCode() : 0);
      result = result * 37 + (end_time != null ? end_time.hashCode() : 0);
      result = result * 37 + (class_type != null ? class_type.hashCode() : 0);
      result = result * 37 + (index != null ? index.hashCode() : 0);
      result = result * 37 + metadata.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) builder.append(", id=").append(id);
    if (section_id != null) builder.append(", section_id=").append(section_id);
    if (room != null) builder.append(", room=").append(room);
    if (day != null) builder.append(", day=").append(day);
    if (start_time != null) builder.append(", start_time=").append(start_time);
    if (end_time != null) builder.append(", end_time=").append(end_time);
    if (class_type != null) builder.append(", class_type=").append(class_type);
    if (index != null) builder.append(", index=").append(index);
    if (!metadata.isEmpty()) builder.append(", metadata=").append(metadata);
    return builder.replace(0, 2, "Meeting{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Meeting, Builder> {
    public Long id;

    public Long section_id;

    public String room;

    public String day;

    public String start_time;

    public String end_time;

    public String class_type;

    public Integer index;

    public List<Metadata> metadata;

    public Builder() {
      metadata = Internal.newMutableList();
    }

    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    public Builder section_id(Long section_id) {
      this.section_id = section_id;
      return this;
    }

    public Builder room(String room) {
      this.room = room;
      return this;
    }

    public Builder day(String day) {
      this.day = day;
      return this;
    }

    public Builder start_time(String start_time) {
      this.start_time = start_time;
      return this;
    }

    public Builder end_time(String end_time) {
      this.end_time = end_time;
      return this;
    }

    public Builder class_type(String class_type) {
      this.class_type = class_type;
      return this;
    }

    public Builder index(Integer index) {
      this.index = index;
      return this;
    }

    public Builder metadata(List<Metadata> metadata) {
      Internal.checkElementsNotNull(metadata);
      this.metadata = metadata;
      return this;
    }

    @Override
    public Meeting build() {
      return new Meeting(id, section_id, room, day, start_time, end_time, class_type, index, metadata, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Meeting extends ProtoAdapter<Meeting> {
    ProtoAdapter_Meeting() {
      super(FieldEncoding.LENGTH_DELIMITED, Meeting.class);
    }

    @Override
    public int encodedSize(Meeting value) {
      return (value.id != null ? ProtoAdapter.INT64.encodedSizeWithTag(1, value.id) : 0)
          + (value.section_id != null ? ProtoAdapter.INT64.encodedSizeWithTag(2, value.section_id) : 0)
          + (value.room != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.room) : 0)
          + (value.day != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.day) : 0)
          + (value.start_time != null ? ProtoAdapter.STRING.encodedSizeWithTag(5, value.start_time) : 0)
          + (value.end_time != null ? ProtoAdapter.STRING.encodedSizeWithTag(6, value.end_time) : 0)
          + (value.class_type != null ? ProtoAdapter.STRING.encodedSizeWithTag(7, value.class_type) : 0)
          + (value.index != null ? ProtoAdapter.INT32.encodedSizeWithTag(8, value.index) : 0)
          + Metadata.ADAPTER.asRepeated().encodedSizeWithTag(9, value.metadata)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Meeting value) throws IOException {
      if (value.id != null) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.id);
      if (value.section_id != null) ProtoAdapter.INT64.encodeWithTag(writer, 2, value.section_id);
      if (value.room != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.room);
      if (value.day != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.day);
      if (value.start_time != null) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.start_time);
      if (value.end_time != null) ProtoAdapter.STRING.encodeWithTag(writer, 6, value.end_time);
      if (value.class_type != null) ProtoAdapter.STRING.encodeWithTag(writer, 7, value.class_type);
      if (value.index != null) ProtoAdapter.INT32.encodeWithTag(writer, 8, value.index);
      Metadata.ADAPTER.asRepeated().encodeWithTag(writer, 9, value.metadata);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Meeting decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.INT64.decode(reader)); break;
          case 2: builder.section_id(ProtoAdapter.INT64.decode(reader)); break;
          case 3: builder.room(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.day(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.start_time(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.end_time(ProtoAdapter.STRING.decode(reader)); break;
          case 7: builder.class_type(ProtoAdapter.STRING.decode(reader)); break;
          case 8: builder.index(ProtoAdapter.INT32.decode(reader)); break;
          case 9: builder.metadata.add(Metadata.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Meeting redact(Meeting value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.metadata, Metadata.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
