// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: model.proto at 127:1
package com.tevinjeffrey.rutgersct.data.model;

import android.os.Parcelable;
import android.support.annotation.Nullable;

import com.squareup.wire.AndroidMessage;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;

import java.io.IOException;

import okio.ByteString;

public final class Response extends AndroidMessage<Response, Response.Builder> {
  public static final ProtoAdapter<Response> ADAPTER = new ProtoAdapter_Response();

  public static final Parcelable.Creator<Response> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.tevinjeffrey.rutgersct.data.model.Meta#ADAPTER"
  )
  @Nullable
  public final Meta meta;

  @WireField(
      tag = 2,
      adapter = "com.tevinjeffrey.rutgersct.data.model.Data#ADAPTER"
  )
  @Nullable
  public final Data data;

  public Response(@Nullable Meta meta, @Nullable Data data) {
    this(meta, data, ByteString.EMPTY);
  }

  public Response(@Nullable Meta meta, @Nullable Data data, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.meta = meta;
    this.data = data;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) {
      return true;
    }
    if (!(other instanceof Response)) {
      return false;
    }
    Response o = (Response) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(meta, o.meta)
        && Internal.equals(data, o.data);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (meta != null ? meta.hashCode() : 0);
      result = result * 37 + (data != null ? data.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.meta = meta;
    builder.data = data;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (meta != null) {
      builder.append(", meta=").append(meta);
    }
    if (data != null) {
      builder.append(", data=").append(data);
    }
    return builder.replace(0, 2, "Response{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Response, Builder> {
    public Meta meta;

    public Data data;

    public Builder() {
    }

    @Override
    public Response build() {
      return new Response(meta, data, super.buildUnknownFields());
    }

    public Builder data(Data data) {
      this.data = data;
      return this;
    }

    public Builder meta(Meta meta) {
      this.meta = meta;
      return this;
    }
  }

  private static final class ProtoAdapter_Response extends ProtoAdapter<Response> {
    ProtoAdapter_Response() {
      super(FieldEncoding.LENGTH_DELIMITED, Response.class);
    }

    @Override
    public Response decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1; ) {
        switch (tag) {
          case 1:
            builder.meta(Meta.ADAPTER.decode(reader));
            break;
          case 2:
            builder.data(Data.ADAPTER.decode(reader));
            break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public void encode(ProtoWriter writer, Response value) throws IOException {
      if (value.meta != null) {
        Meta.ADAPTER.encodeWithTag(writer, 1, value.meta);
      }
      if (value.data != null) {
        Data.ADAPTER.encodeWithTag(writer, 2, value.data);
      }
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public int encodedSize(Response value) {
      return (value.meta != null ? Meta.ADAPTER.encodedSizeWithTag(1, value.meta) : 0)
          + (value.data != null ? Data.ADAPTER.encodedSizeWithTag(2, value.data) : 0)
          + value.unknownFields().size();
    }

    @Override
    public Response redact(Response value) {
      Builder builder = value.newBuilder();
      if (builder.meta != null) {
        builder.meta = Meta.ADAPTER.redact(builder.meta);
      }
      if (builder.data != null) {
        builder.data = Data.ADAPTER.redact(builder.data);
      }
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
